/***************************************************************************
 *   Copyright (C) 2005 by Fred Klaus   *
 *   development@fkweb.de   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

/* DGen font, generated by pbm2df from "dgenfont.pbm" */

#include "bitglyph.h"

namespace sdltk
{
    int BitGlyph::_glyph_20[] = {-1};
    int BitGlyph::_glyph_21[] = {19, 8, 8, 8, 8, 8, 8, 16, -1};
    int BitGlyph::_glyph_22[] = {18, 3, 5, 3, 5, 3, -1};
    int BitGlyph::_glyph_23[] = {26, 3, 5, 3, 4, 1, 1, 1, 1, 1, 4, 3, 4, 1, 1, 1, 1, 1, 4, 3, 5, 3, -1};
    int BitGlyph::_glyph_24[] = {27, 7, 1, 1, 1, 4, 2, 7, 1, 1, 7, 2, 4, 1, 1, 1, 7, -1};
    int BitGlyph::_glyph_25[] = {18, 4, 3, 2, 3, 4, 3, 7, 8, 7, 7, 3, 5, 2, 2, 3, 4, -1};
    int BitGlyph::_glyph_26[] = {34, 1, 6, 3, 5, 3, 6, 1, 6, 3, 2, 3, 4, 5, 1, 1, 2, -1};
    int BitGlyph::_glyph_27[] = {18, 1, 1, 6, 1, 6, -1};
    int BitGlyph::_glyph_28[] = {21, 7, 8, 7, 8, 8, 9, 8, 9, -1};
    int BitGlyph::_glyph_29[] = {18, 9, 8, 9, 8, 8, 7, 8, 7, -1};
    int BitGlyph::_glyph_2A[] = {34, 3, 6, 1, 5, 1, 1, 1, 1, 1, 5, 1, 6, 3, -1};
    int BitGlyph::_glyph_2B[] = {35, 8, 6, 1, 1, 1, 1, 6, 8, -1};
    int BitGlyph::_glyph_2C[] = {74, 1, 1, 6, 1, 6, -1};
    int BitGlyph::_glyph_2D[] = {49, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_2E[] = {75, 7, 1, 1, 7, -1};
    int BitGlyph::_glyph_2F[] = {22, 8, 7, 7, 7, 7, 7, 7, 8, -1};
    int BitGlyph::_glyph_30[] = {19, 1, 6, 3, 4, 5, 3, 5, 3, 5, 3, 5, 3, 5, 4, 3, 6, 1, -1};
    int BitGlyph::_glyph_31[] = {19, 7, 1, 6, 2, 8, 8, 8, 8, 8, 6, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_32[] = {18, 1, 1, 1, 4, 5, 3, 5, 8, 7, 6, 1, 6, 7, 8, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_33[] = {17, 1, 1, 1, 1, 1, 8, 7, 7, 7, 1, 1, 9, 8, 3, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_34[] = {21, 7, 1, 6, 2, 5, 3, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 7, 8, -1};
    int BitGlyph::_glyph_35[] = {17, 1, 1, 1, 1, 1, 3, 8, 8, 2, 1, 1, 4, 1, 4, 8, 8, 3, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_36[] = {19, 1, 1, 5, 7, 8, 8, 2, 1, 1, 4, 1, 4, 3, 5, 3, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_37[] = {17, 1, 1, 1, 1, 1, 8, 7, 7, 8, 7, 8, 7, 8, -1};
    int BitGlyph::_glyph_38[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 5, 4, 1, 1, 1, 4, 5, 3, 5, 3, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_39[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 4, 1, 4, 1, 1, 2, 8, 8, 7, 5, 1, 1, -1};
    int BitGlyph::_glyph_3A[] = {35, 7, 1, 1, 7, 24, 7, 1, 1, 7, -1};
    int BitGlyph::_glyph_3B[] = {35, 7, 1, 1, 7, 23, 1, 1, 6, 1, 6, -1};
    int BitGlyph::_glyph_3C[] = {22, 7, 7, 7, 7, 9, 9, 9, 9, -1};
    int BitGlyph::_glyph_3D[] = {41, 1, 1, 1, 1, 1, 19, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_3E[] = {17, 9, 9, 9, 9, 7, 7, 7, 7, -1};
    int BitGlyph::_glyph_3F[] = {18, 1, 1, 1, 4, 5, 3, 5, 8, 7, 7, 8, 16, -1};
    int BitGlyph::_glyph_40[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 3, 1, 1, 3, 2, 3, 3, 2, 2, 1, 3, 3, 2, 3, 9, 1, 1, 1, -1};
    int BitGlyph::_glyph_41[] = {19, 1, 6, 3, 4, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 1, 3, 5, 3, 5, 3, 5, -1};
    int BitGlyph::_glyph_42[] = {16, 1, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 2, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_43[] = {18, 1, 1, 1, 4, 5, 3, 8, 8, 8, 8, 8, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_44[] = {16, 1, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 2, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_45[] = {17, 1, 1, 1, 1, 1, 3, 8, 8, 8, 1, 1, 1, 5, 8, 8, 8, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_46[] = {17, 1, 1, 1, 1, 1, 3, 8, 8, 8, 1, 1, 1, 5, 8, 8, 8, -1};
    int BitGlyph::_glyph_47[] = {18, 1, 1, 1, 4, 5, 3, 8, 8, 8, 3, 1, 1, 3, 5, 3, 4, 1, 4, 1, 1, 2, -1};
    int BitGlyph::_glyph_48[] = {17, 5, 3, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 1, 3, 5, 3, 5, 3, 5, 3, 5, -1};
    int BitGlyph::_glyph_49[] = {17, 1, 1, 1, 1, 6, 8, 8, 8, 8, 8, 8, 6, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_4A[] = {19, 1, 1, 1, 7, 8, 8, 8, 8, 8, 4, 4, 5, 1, 1, -1};
    int BitGlyph::_glyph_4B[] = {17, 5, 3, 4, 4, 3, 5, 2, 6, 1, 7, 2, 6, 3, 5, 4, 4, 5, -1};
    int BitGlyph::_glyph_4C[] = {17, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_4D[] = {16, 6, 2, 6, 2, 1, 4, 1, 2, 2, 2, 2, 2, 3, 3, 2, 3, 3, 2, 6, 2, 6, 2, 6, -1};
    int BitGlyph::_glyph_4E[] = {17, 5, 3, 5, 3, 1, 4, 3, 2, 3, 3, 3, 2, 3, 4, 1, 3, 5, 3, 5, 3, 5, -1};
    int BitGlyph::_glyph_4F[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_50[] = {17, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 4, 8, 8, 8, -1};
    int BitGlyph::_glyph_51[] = {18, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 2, 3, 3, 3, 2, 4, 1, 1, 1, 9, -1};
    int BitGlyph::_glyph_52[] = {17, 1, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 1, 1, 1, 1, 4, 2, 6, 3, 5, 4, 4, 5, -1};
    int BitGlyph::_glyph_53[] = {18, 1, 1, 1, 4, 5, 3, 8, 9, 1, 1, 1, 9, 8, 3, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_54[] = {16, 1, 1, 1, 1, 1, 1, 5, 8, 8, 8, 8, 8, 8, 8, -1};
    int BitGlyph::_glyph_55[] = {17, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_56[] = {16, 6, 2, 6, 3, 4, 4, 4, 4, 4, 5, 2, 6, 2, 6, 2, 7, -1};
    int BitGlyph::_glyph_57[] = {16, 6, 2, 6, 2, 6, 2, 6, 2, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 2, 3, 4, -1};
    int BitGlyph::_glyph_58[] = {16, 6, 2, 6, 3, 4, 5, 2, 7, 7, 2, 5, 4, 3, 6, 2, 6, -1};
    int BitGlyph::_glyph_59[] = {16, 6, 2, 6, 3, 4, 5, 2, 7, 8, 8, 8, 8, -1};
    int BitGlyph::_glyph_5A[] = {17, 1, 1, 1, 1, 1, 8, 7, 7, 7, 7, 7, 8, 8, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_5B[] = {18, 1, 1, 1, 5, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, -1};
    int BitGlyph::_glyph_5C[] = {16, 8, 9, 9, 9, 9, 9, 9, 8, -1};
    int BitGlyph::_glyph_5D[] = {17, 1, 1, 1, 8, 8, 8, 8, 8, 8, 8, 5, 1, 1, 1, -1};
    int BitGlyph::_glyph_5E[] = {19, 7, 2, 5, 4, -1};
    int BitGlyph::_glyph_5F[] = {88, 1, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_60[] = {18, 1, 1, 7, 1, 9, -1};
    int BitGlyph::_glyph_61[] = {42, 1, 1, 1, 9, 4, 1, 1, 1, 1, 3, 5, 3, 4, 1, 4, 1, 1, 2, -1};
    int BitGlyph::_glyph_62[] = {17, 8, 8, 8, 2, 1, 1, 4, 1, 4, 3, 5, 3, 5, 3, 1, 4, 3, 2, 1, 1, -1};
    int BitGlyph::_glyph_63[] = {42, 1, 1, 1, 4, 5, 3, 8, 8, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_64[] = {22, 8, 8, 4, 1, 1, 2, 3, 4, 1, 3, 5, 3, 5, 3, 4, 1, 4, 1, 1, 2, -1};
    int BitGlyph::_glyph_65[] = {42, 1, 1, 1, 4, 5, 3, 1, 1, 1, 1, 1, 3, 8, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_66[] = {19, 1, 1, 5, 4, 4, 8, 7, 1, 1, 1, 1, 5, 8, 8, 8, -1};
    int BitGlyph::_glyph_67[] = {42, 1, 1, 2, 3, 4, 4, 4, 5, 1, 1, 5, 9, 1, 1, 1, 4, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_68[] = {17, 8, 8, 8, 2, 1, 1, 4, 1, 4, 3, 5, 3, 5, 3, 5, 3, 5, -1};
    int BitGlyph::_glyph_69[] = {27, 15, 1, 8, 8, 8, 8, 6, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_6A[] = {29, 15, 1, 8, 8, 8, 8, 4, 4, 4, 4, 5, 1, 1, -1};
    int BitGlyph::_glyph_6B[] = {17, 8, 8, 8, 4, 4, 3, 5, 1, 1, 6, 3, 5, 4, 4, 5, -1};
    int BitGlyph::_glyph_6C[] = {18, 1, 8, 8, 8, 8, 8, 8, 8, 6, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_6D[] = {40, 1, 1, 2, 1, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 3, 2, 6, -1};
    int BitGlyph::_glyph_6E[] = {41, 2, 1, 1, 4, 1, 4, 3, 5, 3, 5, 3, 5, 3, 5, -1};
    int BitGlyph::_glyph_6F[] = {42, 1, 1, 1, 4, 5, 3, 5, 3, 5, 3, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_70[] = {41, 2, 1, 1, 4, 1, 4, 3, 5, 3, 1, 4, 3, 2, 1, 1, 4, 8, 8, -1};
    int BitGlyph::_glyph_71[] = {42, 1, 1, 2, 3, 4, 1, 3, 5, 3, 4, 1, 4, 1, 1, 2, 8, 8, 8, -1};
    int BitGlyph::_glyph_72[] = {41, 2, 1, 1, 5, 4, 4, 8, 8, 8, -1};
    int BitGlyph::_glyph_73[] = {42, 1, 1, 1, 4, 5, 4, 1, 9, 1, 4, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_74[] = {26, 8, 7, 1, 1, 1, 1, 5, 8, 8, 8, 4, 5, 1, 1, -1};
    int BitGlyph::_glyph_75[] = {41, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 1, 1, 2, -1};
    int BitGlyph::_glyph_76[] = {41, 4, 4, 4, 4, 4, 5, 2, 6, 2, 7, -1};
    int BitGlyph::_glyph_77[] = {40, 6, 2, 6, 2, 3, 3, 2, 3, 3, 2, 2, 2, 2, 3, 4, -1};
    int BitGlyph::_glyph_78[] = {41, 5, 4, 3, 6, 1, 7, 1, 6, 3, 4, 5, -1};
    int BitGlyph::_glyph_79[] = {41, 5, 3, 5, 3, 5, 3, 4, 1, 4, 1, 1, 2, 8, 3, 5, 4, 1, 1, 1, -1};
    int BitGlyph::_glyph_7A[] = {41, 1, 1, 1, 1, 1, 7, 7, 7, 7, 7, 1, 1, 1, 1, 1, -1};
    int BitGlyph::_glyph_7B[] = {20, 1, 1, 5, 8, 9, 6, 1, 9, 7, 8, 9, 1, 1, -1};
    int BitGlyph::_glyph_7C[] = {19, 8, 8, 8, 8, 8, 8, 8, 8, -1};
    int BitGlyph::_glyph_7D[] = {17, 1, 1, 9, 8, 7, 9, 1, 6, 9, 8, 5, 1, 1, -1};
    int BitGlyph::_glyph_7E[] = {18, 3, 4, 2, 2, 4, 3, -1};
    int BitGlyph::_glyph_7F[] = {-1};

    int * BitGlyph::mGlyph[] =
        {
            /* Fill in for the control characters */
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
            BitGlyph::_glyph_20,
            BitGlyph::_glyph_21,
            BitGlyph::_glyph_22,
            BitGlyph::_glyph_23,
            BitGlyph::_glyph_24,
            BitGlyph::_glyph_25,
            BitGlyph::_glyph_26,
            BitGlyph::_glyph_27,
            BitGlyph::_glyph_28,
            BitGlyph::_glyph_29,
            BitGlyph::_glyph_2A,
            BitGlyph::_glyph_2B,
            BitGlyph::_glyph_2C,
            BitGlyph::_glyph_2D,
            BitGlyph::_glyph_2E,
            BitGlyph::_glyph_2F,
            BitGlyph::_glyph_30,
            BitGlyph::_glyph_31,
            BitGlyph::_glyph_32,
            BitGlyph::_glyph_33,
            BitGlyph::_glyph_34,
            BitGlyph::_glyph_35,
            BitGlyph::_glyph_36,
            BitGlyph::_glyph_37,
            BitGlyph::_glyph_38,
            BitGlyph::_glyph_39,
            BitGlyph::_glyph_3A,
            BitGlyph::_glyph_3B,
            BitGlyph::_glyph_3C,
            BitGlyph::_glyph_3D,
            BitGlyph::_glyph_3E,
            BitGlyph::_glyph_3F,
            BitGlyph::_glyph_40,
            BitGlyph::_glyph_41,
            BitGlyph::_glyph_42,
            BitGlyph::_glyph_43,
            BitGlyph::_glyph_44,
            BitGlyph::_glyph_45,
            BitGlyph::_glyph_46,
            BitGlyph::_glyph_47,
            BitGlyph::_glyph_48,
            BitGlyph::_glyph_49,
            BitGlyph::_glyph_4A,
            BitGlyph::_glyph_4B,
            BitGlyph::_glyph_4C,
            BitGlyph::_glyph_4D,
            BitGlyph::_glyph_4E,
            BitGlyph::_glyph_4F,
            BitGlyph::_glyph_50,
            BitGlyph::_glyph_51,
            BitGlyph::_glyph_52,
            BitGlyph::_glyph_53,
            BitGlyph::_glyph_54,
            BitGlyph::_glyph_55,
            BitGlyph::_glyph_56,
            BitGlyph::_glyph_57,
            BitGlyph::_glyph_58,
            BitGlyph::_glyph_59,
            BitGlyph::_glyph_5A,
            BitGlyph::_glyph_5B,
            BitGlyph::_glyph_5C,
            BitGlyph::_glyph_5D,
            BitGlyph::_glyph_5E,
            BitGlyph::_glyph_5F,
            BitGlyph::_glyph_60,
            BitGlyph::_glyph_61,
            BitGlyph::_glyph_62,
            BitGlyph::_glyph_63,
            BitGlyph::_glyph_64,
            BitGlyph::_glyph_65,
            BitGlyph::_glyph_66,
            BitGlyph::_glyph_67,
            BitGlyph::_glyph_68,
            BitGlyph::_glyph_69,
            BitGlyph::_glyph_6A,
            BitGlyph::_glyph_6B,
            BitGlyph::_glyph_6C,
            BitGlyph::_glyph_6D,
            BitGlyph::_glyph_6E,
            BitGlyph::_glyph_6F,
            BitGlyph::_glyph_70,
            BitGlyph::_glyph_71,
            BitGlyph::_glyph_72,
            BitGlyph::_glyph_73,
            BitGlyph::_glyph_74,
            BitGlyph::_glyph_75,
            BitGlyph::_glyph_76,
            BitGlyph::_glyph_77,
            BitGlyph::_glyph_78,
            BitGlyph::_glyph_79,
            BitGlyph::_glyph_7A,
            BitGlyph::_glyph_7B,
            BitGlyph::_glyph_7C,
            BitGlyph::_glyph_7D,
            BitGlyph::_glyph_7E,
            BitGlyph::_glyph_7F
        };

} //namespace sdltk
