/* DGen font, generated by pbm2df from "dgenfont.pbm" */

#ifndef BITGLYPH_H
#define BITGLYPH_H

namespace sdltk
{

    class BitGlyph
    {
    public:
        static int * glyph(int num) {return mGlyph[num];}

    private:
        static int * mGlyph[];

        static int _glyph_20[];
        static int _glyph_21[];
        static int _glyph_22[];
        static int _glyph_23[];
        static int _glyph_24[];
        static int _glyph_25[];
        static int _glyph_26[];
        static int _glyph_27[];
        static int _glyph_28[];
        static int _glyph_29[];
        static int _glyph_2A[];
        static int _glyph_2B[];
        static int _glyph_2C[];
        static int _glyph_2D[];
        static int _glyph_2E[];
        static int _glyph_2F[];
        static int _glyph_30[];
        static int _glyph_31[];
        static int _glyph_32[];
        static int _glyph_33[];
        static int _glyph_34[];
        static int _glyph_35[];
        static int _glyph_36[];
        static int _glyph_37[];
        static int _glyph_38[];
        static int _glyph_39[];
        static int _glyph_3A[];
        static int _glyph_3B[];
        static int _glyph_3C[];
        static int _glyph_3D[];
        static int _glyph_3E[];
        static int _glyph_3F[];
        static int _glyph_40[];
        static int _glyph_41[];
        static int _glyph_42[];
        static int _glyph_43[];
        static int _glyph_44[];
        static int _glyph_45[];
        static int _glyph_46[];
        static int _glyph_47[];
        static int _glyph_48[];
        static int _glyph_49[];
        static int _glyph_4A[];
        static int _glyph_4B[];
        static int _glyph_4C[];
        static int _glyph_4D[];
        static int _glyph_4E[];
        static int _glyph_4F[];
        static int _glyph_50[];
        static int _glyph_51[];
        static int _glyph_52[];
        static int _glyph_53[];
        static int _glyph_54[];
        static int _glyph_55[];
        static int _glyph_56[];
        static int _glyph_57[];
        static int _glyph_58[];
        static int _glyph_59[];
        static int _glyph_5A[];
        static int _glyph_5B[];
        static int _glyph_5C[];
        static int _glyph_5D[];
        static int _glyph_5E[];
        static int _glyph_5F[];
        static int _glyph_60[];
        static int _glyph_61[];
        static int _glyph_62[];
        static int _glyph_63[];
        static int _glyph_64[];
        static int _glyph_65[];
        static int _glyph_66[];
        static int _glyph_67[];
        static int _glyph_68[];
        static int _glyph_69[];
        static int _glyph_6A[];
        static int _glyph_6B[];
        static int _glyph_6C[];
        static int _glyph_6D[];
        static int _glyph_6E[];
        static int _glyph_6F[];
        static int _glyph_70[];
        static int _glyph_71[];
        static int _glyph_72[];
        static int _glyph_73[];
        static int _glyph_74[];
        static int _glyph_75[];
        static int _glyph_76[];
        static int _glyph_77[];
        static int _glyph_78[];
        static int _glyph_79[];
        static int _glyph_7A[];
        static int _glyph_7B[];
        static int _glyph_7C[];
        static int _glyph_7D[];
        static int _glyph_7E[];
        static int _glyph_7F[];
    };


} //namespace sdltk

#endif //BITGLYPH_H

